#!/usr/bin/env node
const fs = require('fs');

if (process.argv.length < 3) {
  console.error(`Usage: ${process.argv[1]} <lang>`);
  process.exit(1);
}
const lang = process.argv[2];
const rules = require(`./language_configs/${lang}.rules.js`);
if (!rules) {
  console.error(`${lang} does not have rules defined`);
  process.exit(1);
}

const langCsvFile = `./mappings/${lang}.csv`;
if (fs.existsSync(langCsvFile)) {
  console.warn(`${lang}.csv already exists!`);
  process.exit(1);
}

const csvHeader = 'RULE,ENABLED,PRETTY_NAME,COLOR,\n';
const reducer = (acc, rule) => `${acc}${rule},0,,\n`;
const csvBody = Object.keys(rules).reduce(reducer, '');
if (!fs.existsSync('./mappings')) {
  fs.mkdirSync('./mappings');
}
fs.writeFileSync(langCsvFile, `${csvHeader}${csvBody}`);
