#!/usr/bin/env bash

# Config begin
LANG_CONFIGS_DIR=language_configs/
CACHE_DIR=_cache/
OUTPUT_DIR=public/langs
MAPPINGS_DIR="mappings"
PUSH_ENV="$1"
VERSION_TAG="$2"

# Config end


if [ "$PUSH_ENV" == "release" ]
then
  echo "Releasing Codesplain Parsers"
elif [ "$PUSH_ENV" == "dev" ]
then
  echo "Updating Codesplain Parsers in dev environment"
  VERSION_TAG="dev"
else
   echo "Error! Invalid PUSH_ENV" 1>&2
   exit 1
fi


rm -rf $CACHE_DIR/treematcher/

# Build and push all parsers to S3 buckets:
for lang_config in $LANG_CONFIGS_DIR/*.compile.js; do
  PARSELANG="$(basename $lang_config .compile.js)"
  printf "Building and publishing $PARSELANG parser\n"

  rm -rf "$CACHE_DIR/$PARSELANG/"
  ./make --lang $PARSELANG --debug >/dev/null
  ./make --lang $PARSELANG --minify >/dev/null

  aws s3 cp $OUTPUT_DIR/$PARSELANG.min.js s3://codesplain-parsers/$PARSELANG/$VERSION_TAG/$PARSELANG.min.js
  aws s3 cp $OUTPUT_DIR/$PARSELANG.js s3://codesplain-parsers/$PARSELANG/$VERSION_TAG/$PARSELANG.js
  aws s3 cp $MAPPINGS_DIR/$PARSELANG.csv s3://codesplain-parsers/$PARSELANG/$VERSION_TAG/$PARSELANG.csv
done

exit
