let TerminalNodeImpl = require('antlr4/tree/Tree.js').TerminalNodeImpl;

module.exports = function(lang_runtime_config, root) {

    // Takes an antlr node generated by the antlr parser, and outputs our simplified node.
    let simplify_node = function(node) {
        if (node instanceof TerminalNodeImpl) {
            let ast_type = lang_runtime_config.symbol_name_map[node.symbol.type + 2];
            return {
                'ast_type': ast_type,
                'tags': [ast_type],
                'begin': node.symbol.start,
                'end': node.symbol.stop + 1,
                'text': node.symbol.text,
                'detail': [],
                'children': [],
            };
        } else {
            let ast_type = lang_runtime_config.rule_name_map[node.ruleIndex];
            return {
                'ast_type': ast_type,
                'tags': [ast_type],
                'begin': node.start.start,
                'end': (node.stop ? node.stop : node.start).stop + 1,
                'detail': [],
                'children': node.children ? node.children.map(simplify_node) : [],
            };
        }
    };

    return simplify_node(root);
};
