// Configuration for each possible node type.
// Currently, the only option is 'collapse', which is used by the collapse transformer.

module.exports = {
    'chunk': {},
    'block': {},
    'stat': {},
    'retstat': {},
    'label': {},
    'funcname': {},
    'varlist': {},
    'namelist': {},
    'explist': {},
    'exp': {},
    'prefixexp': {},
    'functioncall': {},
    'varOrExp': {},
    'var': {},
    'varSuffix': {},
    'nameAndArgs': {},
    'args': {},
    'functiondef': {},
    'funcbody': {},
    'parlist': {},
    'tableconstructor': {},
    'fieldlist': {},
    'field': {},
    'fieldsep': {},
    'operatorOr': {},
    'operatorAnd': {},
    'operatorComparison': {},
    'operatorStrcat': {},
    'operatorAddSub': {},
    'operatorMulDivMod': {},
    'operatorBitwise': {},
    'operatorUnary': {},
    'operatorPower': {},
    'number': {},
    'string': {},
    '._EPSILON': {},
    '._EOF': {},
    '._INVALID': {},
    '.NAME': {},
    '.NORMALSTRING': {},
    '.CHARSTRING': {},
    '.LONGSTRING': {},
    '.INT': {},
    '.HEX': {},
    '.FLOAT': {},
    '.HEX_FLOAT': {},
    '.COMMENT': {},
    '.LINE_COMMENT': {},
    '.WS': {},
    '.SHEBANG': {},
};
