let collapse = require('../app/finalizers.js').collapse;

module.exports = {
	'language': 'Python3',
	'grammar_file': 'Python3.JavaScriptTarget.g4',
	'entry_rule': 'file_input',
	'rules': {
	    'single_input': {'finalizers': []},
	    'file_input': {'finalizers': []},
	    'eval_input': {'finalizers': []},
	    'decorator': {'finalizers': []},
	    'decorators': {'finalizers': [collapse]},
	    'decorated': {'finalizers': [collapse]},
	    'funcdef': {'finalizers': []},
	    'parameters': {'finalizers': []},
	    'typedargslist': {'finalizers': []},
	    'tfpdef': {'finalizers': []},
	    'varargslist': {'finalizers': []},
	    'vfpdef': {'finalizers': [collapse]},
	    'stmt': {'finalizers': [collapse]},
	    'simple_stmt': {'finalizers': []},
	    'small_stmt': {'finalizers': [collapse]},
	    'expr_stmt': {'finalizers': [collapse]},
	    'testlist_star_expr': {'finalizers': [collapse]},
	    'augassign': {'finalizers': []},
	    'del_stmt': {'finalizers': []},
	    'pass_stmt': {'finalizers': []},
	    'flow_stmt': {'finalizers': [collapse]},
	    'break_stmt': {'finalizers': []},
	    'continue_stmt': {'finalizers': []},
	    'return_stmt': {'finalizers': []},
	    'yield_stmt': {'finalizers': []},
	    'raise_stmt': {'finalizers': []},
	    'import_stmt': {'finalizers': [collapse], 'sdb_concept': 'import'},
	    'import_name': {'finalizers': []},
	    'import_from': {'finalizers': []},
	    'import_as_name': {'finalizers': []},
	    'dotted_as_name': {'finalizers': [collapse]},
	    'import_as_names': {'finalizers': [collapse]},
	    'dotted_as_names': {'finalizers': [collapse]},
	    'dotted_name': {'finalizers': [collapse]},
	    'global_stmt': {'finalizers': []},
	    'nonlocal_stmt': {'finalizers': []},
	    'assert_stmt': {'finalizers': []},
	    'compound_stmt': {'finalizers': [collapse]},
	    'if_stmt': {'finalizers': []},
	    'while_stmt': {'finalizers': []},
	    'for_stmt': {'finalizers': []},
	    'try_stmt': {'finalizers': []},
	    'with_stmt': {'finalizers': []},
	    'with_item': {'finalizers': []},
	    'except_clause': {'finalizers': []},
	    'suite': {'finalizers': [collapse]},
	    'test': {'finalizers': [collapse]},
	    'test_nocond': {'finalizers': [collapse]},
	    'lambdef': {'finalizers': []},
	    'lambdef_nocond': {'finalizers': []},
	    'or_test': {'finalizers': [collapse]},
	    'and_test': {'finalizers': [collapse]},
	    'not_test': {'finalizers': [collapse]},
	    'comparison': {'finalizers': [collapse]},
	    'comp_op': {'finalizers': []},
	    'star_expr': {'finalizers': [collapse]},
	    'expr': {'finalizers': []},
	    'xor_expr': {'finalizers': [collapse]},
	    'and_expr': {'finalizers': [collapse]},
	    'shift_expr': {'finalizers': [collapse]},
	    'arith_expr': {'finalizers': [collapse]},
	    'term': {'finalizers': [collapse]},
	    'factor': {'finalizers': [collapse]},
	    'power': {'finalizers': [collapse]},
	    'trailed_atom': {'finalizers': [collapse]},
	    'atom': {'finalizers': []},
	    'testlist_comp': {'finalizers': []},
	    'trailer': {'finalizers': []},
	    'subscriptlist': {'finalizers': [collapse]},
	    'subscript': {'finalizers': [collapse]},
	    'sliceop': {'finalizers': []},
	    'exprlist': {'finalizers': [collapse]},
	    'testlist': {'finalizers': [collapse]},
	    'dictorsetmaker': {'finalizers': []},
	    'classdef': {'finalizers': []},
	    'arglist': {'finalizers': [collapse]}, // This probably won't ever actually collapse, due to the arguments in the list being csv
	    'argument': {'finalizers': []},
	    'comp_iter': {'finalizers': [collapse]},
	    'comp_for': {'finalizers': []},
	    'comp_if': {'finalizers': []},
	    'yield_expr': {'finalizers': []},
	    'yield_arg': {'finalizers': [collapse]},
	    'str': {'finalizers': []},
	    'number': {'finalizers': [collapse]},
	    'integer': {'finalizers': []},
	},
};
