const path = require('path');
const antlr = require('antlr4');

const parser_version = require('PackageJson').version;

const lang_runtime_config = require('LangRuntimeConfig');

require('LangCache/runtime_config_modifier.js')(lang_runtime_config);

const lexer_classname = lang_runtime_config.language + 'Lexer';
const parser_classname = lang_runtime_config.language + 'Parser';

// Loads the lexer and parser class generated by the antlr compiler.
const LexerClass = require('LangCache/' + lexer_classname + '.js')[lexer_classname];
const ParserClass = require('LangCache/' + parser_classname + '.js')[parser_classname];

// Loads our custom error listener.
const ErrorListener = require('App/error_listener');

// Loads the transformers
const transformers = require('App/transformers');


// This is the function that is exposed to the UI.
// It takes a string of code, and returns an abstract syntax tree.
// It combines three external things: the antlr lexer, the antlr parser, and our runtime language config.
module.exports = function(input, error_callback, options) {
    lang_runtime_config.call_options = options || {};

    // Take the string of code, and generate a stream of tokens using the antlr lexer.
    // Example: ['if', '(', 'var', '==', '123', ')', '{', ...]
    const chars = new antlr.InputStream(input);
    const lexer = new LexerClass(chars);
    const tokens = new antlr.CommonTokenStream(lexer);

    // Take the stream of tokens, and create a parser class using the antlr parser.
    // Doesn't execute it yet.
    const parser = new ParserClass(tokens);

    // I don't know what this does
    parser.buildParseTrees = true;

    // Antlr has a default error listener that calls console.error. We need to remove it.
    parser.removeErrorListeners();

    // Add our own error listener
    parser.addErrorListener(new ErrorListener(error_callback));

    // Execute the parser and generate a tree.
    // This tree has complicated nodes that need to be simplified by our process_node function.
    const tree = parser[lang_runtime_config.entry_rule]();

    // Transform the tree and return it
    const ast = transformers(lang_runtime_config, tree);

    return {
        'parser_version': parser_version,
        'ast': ast,
    };
};

module.exports['rules'] = lang_runtime_config.rules;
