module.exports = {
    'language': 'TreeMatcher',
    'entry_rule': 'main',
    'rules': {
        'main': {},
        'expr': {},
        'atom': {},
        'expr_atom': {},
        'wildcard': {},
        'search': {},
        'searchable_atom': {},
        'node': {},
        'mod_type': {},
        'mod_terminal': {},
        'mod_store': {},
        'mod_eq_id': {},
        'mod_eq_json_string': {},
        'mod_fixed_children': {},
        'mod_fixed_child': {},
        'mod_variable_children': {},
        'mod_variable_child': {},
        'expr_list': {},
        '._EPSILON': {},
        '._EOF': {},
        '._INVALID': {},
        '.WS': {},
        '.IDENTIFIER': {},
        '.JSON_STRING': {},
    }
};
